import React, { useState } from 'react';
import { UserProfile } from '../types';
import { THEMES } from '../constants';
import { ArrowRight, Sparkles, User, Briefcase, Calendar } from 'lucide-react';
import DeathClock from './DeathClock';

interface OnboardingProps {
  onComplete: (profile: UserProfile) => void;
}

const Onboarding: React.FC<OnboardingProps> = ({ onComplete }) => {
  // Initialize state from URL params or defaults
  const params = new URLSearchParams(window.location.search);
  const defaultName = params.get('name') || 'TV';
  const defaultAge = params.get('age') ? Number(params.get('age')) : 57;
  // Handle assets: if passed in URL use it, otherwise default. The AI uses it as a string description.
  const defaultAssetString = params.get('assets') || '3 millions';

  const [step, setStep] = useState(1);
  const [name, setName] = useState(defaultName);
  const [age, setAge] = useState<number | ''>(defaultAge);
  const [assets, setAssets] = useState<string[]>(defaultAssetString ? [defaultAssetString] : []);
  const [dream, setDream] = useState('');
  const [selectedVibe, setSelectedVibe] = useState<string>('Chaotic Good');
  const [leaveToParasites, setLeaveToParasites] = useState(false);

  const handleNext = () => setStep(prev => prev + 1);

  const handleSubmit = () => {
    if (!age || !name) return;
    onComplete({
      name,
      age: Number(age),
      assets: assets.join(', '),
      dream,
      vibe: selectedVibe,
      theme: '', // Will be generated by AI
    });
  };

  return (
    <div className="max-w-2xl mx-auto p-6">
      <div className="mb-8 text-center">
        <h1 className="text-3xl md:text-4xl font-serif font-bold text-safewill-navy mb-2 flex items-center justify-center gap-2">
          Safewill BucketQuest <Sparkles className="text-safewill-gold" />
        </h1>
        <p className="text-slate-600">Design a legacy that's as unique as you are, to help you complete your goal.</p>
      </div>

      <div className="bg-white rounded-2xl shadow-xl p-8 border border-slate-100">
        {/* Progress Dots */}
        <div className="flex justify-center gap-2 mb-8">
          {[1, 2, 3].map(i => (
            <div key={i} className={`h-2 w-2 rounded-full transition-colors ${step >= i ? 'bg-safewill-teal' : 'bg-slate-200'}`} />
          ))}
        </div>

        {step === 1 && (
          <div className="space-y-6 animate-fade-in">
            <h2 className="text-2xl font-bold text-safewill-blue text-center">Welcome Back</h2>
            
            {/* Death Clock Hero */}
            <div className="py-6 bg-slate-50 rounded-xl border border-slate-100">
               <DeathClock age={Number(age)} />
            </div>

            {/* Read-only Profile Summary */}
            <div className="grid gap-4">
              <div className="p-4 bg-white border border-slate-200 rounded-xl flex items-center gap-4">
                 <div className="bg-blue-50 p-3 rounded-full text-safewill-blue"><User size={20} /></div>
                 <div>
                   <p className="text-xs text-slate-500 font-bold uppercase">Name</p>
                   <p className="font-bold text-lg text-safewill-navy">{name}</p>
                 </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-white border border-slate-200 rounded-xl flex items-center gap-4">
                   <div className="bg-amber-50 p-3 rounded-full text-amber-600"><Calendar size={20} /></div>
                   <div>
                     <p className="text-xs text-slate-500 font-bold uppercase">Age</p>
                     <p className="font-bold text-lg text-safewill-navy">{age}</p>
                   </div>
                </div>
                <div className="p-4 bg-white border border-slate-200 rounded-xl flex items-center gap-4">
                   <div className="bg-green-50 p-3 rounded-full text-green-600"><Briefcase size={20} /></div>
                   <div>
                     <p className="text-xs text-slate-500 font-bold uppercase">Assets</p>
                     <p className="font-bold text-lg text-safewill-navy truncate">{assets[0]}</p>
                   </div>
                </div>
              </div>
            </div>

            <button 
              onClick={handleNext}
              className="w-full mt-6 bg-safewill-navy text-white py-4 rounded-xl font-bold hover:bg-safewill-blue transition-colors flex items-center justify-center gap-2 text-lg"
            >
              Continue to Vibe Check <ArrowRight size={20} />
            </button>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-6 animate-fade-in">
            <h2 className="text-2xl font-bold text-safewill-blue">What's your vibe?</h2>
            <p className="text-slate-500 text-sm">Choose a theme for your life's next chapter.</p>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {THEMES.map(theme => {
                const Icon = theme.icon;
                return (
                  <button
                    key={theme.id}
                    onClick={() => setSelectedVibe(theme.id)}
                    className={`p-4 rounded-xl border text-left transition-all relative overflow-hidden group ${
                      selectedVibe === theme.id 
                        ? 'border-safewill-teal bg-safewill-light ring-2 ring-safewill-teal ring-opacity-50' 
                        : 'border-slate-200 hover:border-safewill-teal hover:shadow-md'
                    }`}
                  >
                    <div className="flex items-center gap-3 mb-2">
                      <div className={`p-2 rounded-lg ${selectedVibe === theme.id ? 'bg-white' : 'bg-slate-100'}`}>
                        <Icon size={20} className={selectedVibe === theme.id ? 'text-safewill-teal' : 'text-slate-600'} />
                      </div>
                      <span className="font-bold text-safewill-blue">{theme.label}</span>
                    </div>
                    <p className="text-xs text-slate-600">{theme.description}</p>
                  </button>
                );
              })}
            </div>

            <button 
              onClick={handleNext}
              className="w-full mt-6 bg-safewill-navy text-white py-3 rounded-xl font-bold hover:bg-safewill-blue transition-colors flex items-center justify-center gap-2"
            >
              Next <ArrowRight size={20} />
            </button>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-6 animate-fade-in">
             <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-safewill-blue">The Vision</h2>
                <div className="scale-75 origin-right">
                  <DeathClock age={Number(age)} compact />
                </div>
             </div>
             
             <div>
               <label className="block text-lg font-medium text-slate-700 mb-2">
                 What do you want to do with the rest of your life?
               </label>
               <p className="text-sm text-slate-500 mb-3">Don't overthink it. Be silly, be serious, be you. We'll use this and your "{selectedVibe}" vibe to generate your list.</p>
               <textarea 
                 value={dream}
                 onChange={(e) => setDream(e.target.value)}
                 className="w-full p-4 h-32 rounded-xl border border-slate-300 bg-slate-50 text-slate-900 focus:ring-2 focus:ring-safewill-teal focus:border-transparent outline-none resize-none"
                 placeholder="I want to visit every continent, learn to tango, and maybe finally organize my digital photos..."
               />
             </div>

             <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 flex items-center gap-3">
               <input 
                 type="checkbox" 
                 id="parasites"
                 checked={leaveToParasites}
                 onChange={(e) => setLeaveToParasites(e.target.checked)}
                 className="w-5 h-5 rounded border-slate-300 text-safewill-navy focus:ring-safewill-teal"
               />
               <label htmlFor="parasites" className="text-sm text-slate-700 font-medium cursor-pointer select-none">
                 Do you want to leave anything to parasites? 🦠
               </label>
             </div>

             <button 
               onClick={handleSubmit}
               disabled={!dream}
               className="w-full mt-4 bg-gradient-to-r from-safewill-navy to-indigo-900 text-white py-4 rounded-xl font-bold hover:shadow-lg transition-all flex items-center justify-center gap-2 text-lg transform hover:-translate-y-0.5"
             >
               Generate My BucketQuest <Sparkles size={20} className="text-safewill-gold" />
             </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Onboarding;